zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

zuul.ribbon-isolation-strategy: thread
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000
hystrix.threadpool.HystrixThreadPoolKey.coreSize: 20

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    fetchRegistry: true